name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests credentials
        run: cargo test --verbose --package credentials -- --test-threads=1
      - name: Run tests file_processing
        run: cargo test --verbose --package file_processing
      - name: Run tests wdapty
        run: cargo test --verbose
